FORMAT: 1A
HOST: http://docs.spool.apiary.io/#

# ascribe SPOOL REST API

Title: ascribe REST API
Description: Main RESTful API for ascribe ownership web service. https://www.ascribe.io
First public release: 2015-04-26
Current public release: 2015-07-01, version 0.1
